apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace

resources:
- deployment.yaml
secretGenerator:
- files:
  - application.properties
  name: database-creds
  
images:
- name: my-app
  newName: "12.5"
- name: myrepo.dkr.ecr.eu-central-1.amazonaws.com/my-app
  newTag: "20230830044213"
